# Generated by Django 6.1.1 on 2026-09-23 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def map_vendor_names(apps, schema_editor):
    """
    Preserve legacy free-text vendor names: create a Vendor row for each
    distinct name and link the materials to it.
    """
    Material = apps.get_model("core", "Material")
    Vendor = apps.get_model("core", "Vendor")
    for material in Material.objects.all():
        raw = (material.vendor_legacy or "").strip()
        if not raw:
            continue
        vendor, _ = Vendor.objects.get_or_create(name=raw)
        material.vendor = vendor
        material.save(update_fields=["vendor"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_overhead_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='skumaterialrequirement',
            old_name='qty_per_bottle',
            new_name='qty_per_case',
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_of_measure',
            field=models.CharField(default='cases', max_length=30),
        ),
        # Material.vendor goes from free text to a Vendor FK. Done in three
        # steps (rename legacy -> add FK -> copy names -> drop legacy) so the
        # existing vendor names are never lost.
        migrations.RenameField(
            model_name='material',
            old_name='vendor',
            new_name='vendor_legacy',
        ),
        migrations.AddField(
            model_name='material',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='core.vendor'),
        ),
        migrations.RunPython(map_vendor_names, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='material',
            name='vendor_legacy',
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.vendor')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]

