# Generated by Django 6.1.1 on 2026-09-23 16:13

from django.db import migrations, models


def _populate_base_cogs(apps, schema_editor):
    """
    For every existing delivery, backfill base_cogs_per_case_snapshot as the
    frozen DIRECT cost per case (materials + print) recomputed from the FIFO
    batch(es) that exist in the DB at migration time. Materials are physical,
    so the batches still carry the original purchase prices and we replay FIFO
    consumption in memory (batches are NOT saved during the replay).

    The cogs_per_case_snapshot (snapshot at creation = base + that month's OH)
    is NOT touched. Going forward the live COGS = base + the delivery month's
    CURRENT overhead, so later overhead/labour edits flow through to every
    delivery of that month (user request).
    """
    from decimal import Decimal, getcontext
    from django.db.models import Sum

    getcontext().prec = 28
    StockDelivery = apps.get_model('core', 'StockDelivery')
    MonthlyOverhead = apps.get_model('core', 'MonthlyOverhead')
    MaterialBatch = apps.get_model('core', 'MaterialBatch')
    SKUPrintCost = apps.get_model('core', 'SKUPrintCost')
    TWO_PLACES = Decimal('0.01')

    def month_key(d):
        return f"{d.year:04d}-{d.month:02d}"

    def overhead_for_month(month_str):
        return (
            MonthlyOverhead.objects.filter(month=month_str)
            .aggregate(s=Sum('amount'))['s']
            or Decimal('0')
        ).quantize(TWO_PLACES)

    def overhead_per_case(month_str, additional_cases=Decimal('0')):
        oh = overhead_for_month(month_str)
        year, mon = (int(p) for p in month_str.split('-'))
        cases = (
            StockDelivery.objects.filter(
                is_deleted=False, date__year=year, date__month=mon
            ).aggregate(s=Sum('qty_cases'))['s']
            or Decimal('0')
        ) + Decimal(additional_cases)
        if cases <= 0 or oh <= 0:
            return Decimal('0')
        return (oh / cases).quantize(TWO_PLACES)

    for delivery in StockDelivery.objects.order_by('date', 'id'):
        if delivery.qty_cases is None or delivery.qty_cases <= 0:
            continue
        month_str = month_key(delivery.date)
        # The frozen base is the snapshot minus the overhead that was live
        # at the time the snapshot was taken (i.e. the overhead pool divided
        # by the cases sold in that month BEFORE this delivery, plus this one).
        # This ensures that later overhead/labour edits for the month flow
        # through to every delivery of that month (user request).
        # NOTE: if the pool was corrupted/zeroed since creation, oh_pool is
        # unreliable — backfill only when we can reconstruct a positive base.
        oh_pool = (
            MonthlyOverhead.objects.filter(month=month_str)
            .aggregate(s=Sum('amount'))['s']
            or Decimal('0')
        )
        if oh_pool <= 0:
            continue
        cases_before = StockDelivery.objects.filter(
            is_deleted=False,
            date__year=delivery.date.year,
            date__month=delivery.date.month,
            date__lt=delivery.date,
        ).aggregate(s=Sum('qty_cases'))['s'] or Decimal('0')
        cases_same_day_before = StockDelivery.objects.filter(
            is_deleted=False, date=delivery.date, id__lt=delivery.id
        ).aggregate(s=Sum('qty_cases'))['s'] or Decimal('0')
        total_cases_at_creation = (
            cases_before + cases_same_day_before + delivery.qty_cases
        )
        oh_per_case_at_creation = (
            oh_pool / total_cases_at_creation
            if total_cases_at_creation > 0
            else Decimal('0')
        ).quantize(TWO_PLACES)
        if delivery.cogs_per_case_snapshot > 0 and oh_per_case_at_creation > 0:
            base = (
                delivery.cogs_per_case_snapshot - oh_per_case_at_creation
            ).quantize(TWO_PLACES)
            if base > 0:
                delivery.base_cogs_per_case_snapshot = base
                delivery.save(skip_audit=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyoverhead',
            name='is_labour_rollup',
        ),
        migrations.RemoveField(
            model_name='monthlyoverhead',
            name='is_manual_override',
        ),
        migrations.AddField(
            model_name='stockdelivery',
            name='base_cogs_per_case_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(_populate_base_cogs, migrations.RunPython.noop),
    ]
