# Generated by Django 6.1.1 on 2026-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_monthlyoverhead_is_labour_rollup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pending_as_of_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='client',
            name='pending_as_of_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payable_as_of_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payable_as_of_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
