# Generated by Django 6.1.1 on 2026-10-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client_pending_as_of_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdelivery',
            name='consumption_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
