# Generated by Django 6.1.1 on 2026-10-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('x_forwarded_for', models.CharField(blank=True, default='', max_length=300)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('locked_out', models.BooleanField(default=False)),
                ('geo_country', models.CharField(blank=True, default='', max_length=100)),
                ('geo_region', models.CharField(blank=True, default='', max_length=150)),
                ('geo_city', models.CharField(blank=True, default='', max_length=150)),
                ('geo_isp', models.CharField(blank=True, default='', max_length=200)),
                ('geo_source', models.CharField(blank=True, default='', max_length=20)),
                ('geo_error', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['ip', 'timestamp'], name='login_ip_ts_idx')],
            },
        ),
    ]
