# Generated by Django 6.1.1 on 2026-10-10 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clientorder_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_orders', to='core.clientorder'),
        ),
    ]
